# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Just Enough IT Leadership
email: fran@franfabrizio.com
description: >- # this means to ignore newlines until "baseurl:"
  Just Enough IT Management is a blog for all the IT professionals out there
  who wake up one day and find themselves in a leadership role. This blog discusses
  how to be a pragmatic and effective leader and manager while staying true to your
  techie roots.
baseurl: "/just-enough-it-leadership" # the subpath of your site, e.g. /blog
url: "http://blog.franfabrizio.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: franfabrizio
github_username:  franfabrizio

# Build settings
markdown: kramdown
remote_theme: mmistakes/jekyll-theme-basically-basic
plugins:
  - jekyll-feed

author:
  name: Fran Fabrizio
  twitter: franfabrizio

# does this work globally if I put it here?
read_time: true

disqus:
  shortname: just-enough-it-leadership

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
